version: '3'

services:
  web-php:
    container_name: assessment-web-php
    tty: true
    build:
      context: ./web-php/
    volumes:
      - ./assessment-www:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      assessment-web-network:
        ipv4_address: 170.17.241.125
  nginx:
    container_name: assessment-web-nginx
    image: nginx:1.20.0
    ports:
      - "81:80"
    depends_on:
      - web-php
    volumes:
      - ./web-nginx:/etc/nginx/conf.d/
      - ./assessment-www:/var/www
    networks:
      assessment-web-network:
        ipv4_address: 170.17.241.254
  
networks:
  assessment-web-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 170.17.241.0/24
