questions:
  path: /questions
  controller: App\Infrastructure\Http\QuestionsController
  methods: GET
create-questions:
  path: /questions
  controller: App\Infrastructure\Http\CreateQuestionController
  methods: POST